package com.arabsoft.ajir.dao;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.arabsoft.ajir.entities.CleContrat;
import com.arabsoft.ajir.entities.Contrat;

public interface ContratRep extends JpaRepository<Contrat, CleContrat>{
	
	
	
	@Query(value="select cod_soc, \r\n"
			+ "mat_pers, \r\n"
			+ "num_contrat, \r\n"
			+ "cod_typ, \r\n"
			+ "etat, \r\n"
			+ "nat_contrat, \r\n"
			+ "num_num_contrat, \r\n"
			+ "dat_contrat, \r\n"
			+ "dat_ech, \r\n"
			+ "cod_motif, \r\n"
			+ "cod_dept, \r\n"
			+ "cod_serv, \r\n"
			+ "mnt_mens, \r\n"
			+ "cod_eva, \r\n"
			+ "date_eva, \r\n"
			+ "cod_niveau, \r\n"
			+ "valid, \r\n"
			+ "duree, \r\n"
			+ "cod_fill, \r\n"
			+ "num_ord, \r\n"
			+ "dat_eff_contrat, \r\n"
			+ "dat_ord, \r\n"
			+ "edit, \r\n"
			+ "dat_creation, \r\n"
			+ "dat_valid, \r\n"
			+ "nouv_motif, \r\n"
			+ "duree_essai, \r\n"
			+ "cod_affect, \r\n"
			+ "num_mvt, \r\n"
			+ "cod_alert, \r\n"
			+ "seq_alert, \r\n"
			+ "nadm_tech, \r\n"
			+ "ncod_affect, \r\n"
			+ "ncod_serv, \r\n"
			+ "nbr_pts, \r\n"
			+ "cod_cat, \r\n"
			+ "cod_grad, \r\n"
			+ "cod_categ, \r\n"
			+ "cod_ech, \r\n"
			+ "niv_sal, \r\n"
			+ "dat_rupture, \r\n"
			+ "typ_salaire, \r\n"
			+ "ncod_categ, \r\n"
			+ "ncod_cat, \r\n"
			+ "ncod_grad, \r\n"
			+ "ncod_ech, \r\n"
			+ "ncod_stat, \r\n"
			+ "pk_get_lib.Get_personnel$NomPrenom(cod_soc,mat_pers) nom_pren,\r\n"
			+ "pk_get_lib.GET_TYPE_CONTR$LIB_TYP(cod_typ) lib_contrat \r\n"
			+ "from contrat c\r\n"
			+ "where  c.valid in ('O','P')",nativeQuery=true)
	public List<Contrat> getContrat();
	
	@Query(value="select c.cod_soc, \r\n"
			+ "c.mat_pers, \r\n"
			+ "num_contrat, \r\n"
			+ "cod_typ, \r\n"
			+ "etat, \r\n"
			+ "nat_contrat, \r\n"
			+ "num_num_contrat, \r\n"
			+ "dat_contrat, \r\n"
			+ "c.dat_ech, \r\n"
			+ "c.cod_motif, \r\n"
			+ "cod_dept, \r\n"
			+ "c.cod_serv, \r\n"
			+ "mnt_mens, \r\n"
			+ "cod_eva, \r\n"
			+ "date_eva, \r\n"
			+ "c.cod_niveau, \r\n"
			+ "valid, \r\n"
			+ "duree, \r\n"
			+ "c.cod_fill, \r\n"
			+ "num_ord, \r\n"
			+ "dat_eff_contrat, \r\n"
			+ "dat_ord, \r\n"
			+ "edit, \r\n"
			+ "dat_creation, \r\n"
			+ "dat_valid, \r\n"
			+ "nouv_motif, \r\n"
			+ "duree_essai, \r\n"
			+ "c.cod_affect, \r\n"
			+ "num_mvt, \r\n"
			+ "cod_alert, \r\n"
			+ "seq_alert, \r\n"
			+ "nadm_tech, \r\n"
			+ "ncod_affect, \r\n"
			+ "ncod_serv, \r\n"
			+ "nbr_pts, \r\n"
			+ "c.cod_cat, \r\n"
			+ "c.cod_grad, \r\n"
			+ "c.cod_categ, \r\n"
			+ "c.cod_ech, \r\n"
			+ "c.niv_sal, \r\n"
			+ "dat_rupture, \r\n"
			+ "typ_salaire, \r\n"
			+ "ncod_categ, \r\n"
			+ "ncod_cat, \r\n"
			+ "ncod_grad, \r\n"
			+ "ncod_ech, \r\n"
			+ "ncod_stat, \r\n"

			+ "pk_get_lib.Get_personnel$NomPrenom(c.cod_soc,c.mat_pers) nom_pren,\r\n"
			+ "pk_get_lib.GET_TYPE_CONTR$LIB_TYP(cod_typ) lib_contrat \r\n"
			+ "from contrat c,personnel p\r\n"
			+ "\r\n"
			+ "where c.cod_soc = p.cod_soc\r\n"
			+ "   and c.mat_pers= p.mat_pers \r\n"
			+ "   and c.dat_ech between to_date(:date1,'yyyy-MM-dd')  and to_date(:date2,'yyyy-MM-dd')",nativeQuery=true)
	 	public List<Contrat> getEndContrat(@Param("date1") String date1,@Param("date2") String date2);
	
	
	@Query(value="select cod_soc, \r\n"
			+ "mat_pers, \r\n"
			+ "num_contrat, \r\n"
			+ "cod_typ, \r\n"
			+ "etat, \r\n"
			+ "nat_contrat, \r\n"
			+ "num_num_contrat, \r\n"
			+ "dat_contrat, \r\n"
			+ "dat_ech, \r\n"
			+ "cod_motif, \r\n"
			+ "cod_dept, \r\n"
			+ "cod_serv, \r\n"
			+ "mnt_mens, \r\n"
			+ "cod_eva, \r\n"
			+ "date_eva, \r\n"
			+ "cod_niveau, \r\n"
			+ "valid, \r\n"
			+ "duree, \r\n"
			+ "cod_fill, \r\n"
			+ "num_ord, \r\n"
			+ "dat_eff_contrat, \r\n"
			+ "dat_ord, \r\n"
			+ "edit, \r\n"
			+ "dat_creation, \r\n"
			+ "dat_valid, \r\n"
			+ "nouv_motif, \r\n"
			+ "duree_essai, \r\n"
			+ "cod_affect, \r\n"
			+ "num_mvt, \r\n"
			+ "cod_alert, \r\n"
			+ "seq_alert, \r\n"
			+ "nadm_tech, \r\n"
			+ "ncod_affect, \r\n"
			+ "ncod_serv, \r\n"
			+ "nbr_pts, \r\n"
			+ "cod_cat, \r\n"
			+ "cod_grad, \r\n"
			+ "cod_categ, \r\n"
			+ "cod_ech, \r\n"
			+ "niv_sal, \r\n"
			+ "dat_rupture, \r\n"
			+ "typ_salaire, \r\n"
			+ "ncod_categ, \r\n"
			+ "ncod_cat, \r\n"
			+ "ncod_grad, \r\n"
			+ "ncod_ech, \r\n"
			+ "ncod_stat, \r\n"

			+ "pk_get_lib.Get_personnel$NomPrenom(cod_soc,mat_pers) nom_pren,\r\n"
			+ "pk_get_lib.GET_TYPE_CONTR$LIB_TYP(cod_typ) lib_contrat \r\n"
			+ "from contrat c\r\n"
			+ "where c.cod_soc=:cod and c.mat_pers=:mat and c.num_contrat=:num  ",nativeQuery=true)
	public List<Contrat> getContratById(@Param("cod") String cod,@Param("mat") String mat,@Param("num") Integer num);


}
